### ISSUE TITLE
M32 Show control and select/solo

### ISSUE THREAD

**Issue by Gaiamus** [bitfocus/companion-module-x32#1]
Is it possible to add show control buttons for M32/X32? I've got a M32r, the show control buttons are missing on the console and I cannot chose these functions as a user define key on the console. This issue would be sovled by scene buttons for "Last", "next", "undo" and "GO".

Also, it would be awesome to be able to choose "solo" and/or "select for a mix bus when doing monitors from the console. In this way I can set the console to select follows solo or solo follows select. When I press a the button I will then hear the mix in my wedge and att the same time flip the faders on the console for that mix. The dream for all monitor techs using this console!

**Comment by PerRoine** [comment]
Added Select for all channels busses and auxes

**Comment by stevenforster** [comment]
Hello,  I've just learned of using a Stream Deck with Companion and what a game changer it is for most of my workflow... I see that someone else asked about capabilities for Solo-ing a channel/Bus on an X/M32. Is this something that can be done?

**Comment by JeffreyDavidsz** [comment]
It would be helpful if you could check if there is a command for it, when there is. Just post it here. Than it can be added

**Comment by Gaiamus** [comment]
/-stat/solosw/[id] | int | 0/1 for on/off of solo switch
-- | -- | --
  |   | [id] 0-31: Ch 1-32
  |   | [id] 32-63: Ch 32-64
  |   | [id] 64-47: Aux in /USB
  |   | [id] 48-63: Bus master
  |   | [id] 64-69: Matrix 1-6
  |   | [id] 70: L/R
  |   | [id] 71: Mono/Center
