### ISSUE TITLE
x32 snippet won't load

### ISSUE THREAD

**Issue by dwashingtontv** [bitfocus/companion-module-x32#4]
When I try to load an Behringer X32 console snippet, nothing happens. I know the stream deck and companion are setup correctly because I can get companion to execute other commands, such as load console scene, set mute, set level, etc.  I have eight snippets in positions 00 through 07. I have tried putting values of 00, 01, 0, 1, etc., in the options column with no luck.

**To Reproduce**
Add Load Console snippet, add a value in the options column. Nothing happens.

**Expected behavior**
The selected snippet is loaded in the x32.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
The X32 is able to load snippets on the console. The issue is when I try to use the Stream Deck via Companion. Companion / Stream Deck will not load the selected snippet.

**Comment by PerRoine** [comment]
Fixed issue thx to Haakon for spotting short vs long dash in the path copy/paste mistake there

**Comment by dwashingtontv** [comment]
That fixed it - thank you!

**Comment by eventwebcasting** [comment]
I am having the same issues and don't understand how you fixed it.. can you please explain a little further.

Thank you!

**Comment by tane650** [comment]
Same issue can someone explain how to fix this?

**Comment by eventwebcasting** [comment]
Which version are you using... I have been using 2.0 and it’s working fine... uninstall the native SD app...

In the X32 there are 2 places for snipers... I don’t know why... the one on the right works and you need to make sure to turn off the pop up confirmation box in settings... and make snippets the default load.

Michael Baker
Event Webcasting
Live Video Productions & More
C: 919.673.3787

www.Event-Webcasting.com
Sports  - Concerts - Festivals

**Comment by tane650** [comment]
I'm on X32/M32 1.0.0 , I guess from when I downloaded companion v 1.3 - How do I update to version 2.0? And thanks for the extra advice, all was already set up like you said with the console and it's defaults. And how/why uninstall the native SD app? Sorry I'm new to companion but enjoying what it can do.

**Comment by eventwebcasting** [comment]
I don’t think 1.3 proper has the X32 plugin... I also think there is a 1.4 out there which is considered semi stable... it’s in the repository...

Michael Baker
Event Webcasting
Live Video Productions & More
C: 919.673.3787

www.Event-Webcasting.com
Sports  - Concerts - Festivals
